### ISSUE TITLE
guild.i18n.setLocale() change the locale of all the guilds

### ISSUE THREAD

**Issue by Lexedia** [Rapougnac/Kiwiibot-typescript#9]
I don't know what this cause that, needs investigation

**Comment by Lexedia** [comment]
This bug appear with the [#mysql](https://github.com/Rapougnac/Kiwiibot-typescript/tree/mysql) branch.

**Comment by Rapougnac** [comment]
> This bug appear with the [#mysql](https://github.com/Rapougnac/Kiwiibot-typescript/tree/mysql?rgh-link-date=2021-12-13T14%3A52%3A22Z) branch.

And, no, this was caused by the disparition of Structures.
